name: Live Proposal Integration Tests
on: [pull_request]

env:
  OP_RPC_URL: ${{secrets.OP_RPC_URL}}
  BASE_RPC_URL: ${{secrets.BASE_RPC_URL}}
  MOONBEAM_RPC_URL: ${{secrets.MOONBEAM_RPC_URL}}

jobs:
  run-live-proposals-integration-tests:
    name: live-proposals-integration-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions

      - name: Live Proposal Integration Tests
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x bin/get-latest-base-proposal.sh
          chmod +x bin/get-latest-moonbeam-proposal.sh
          chmod +x src/proposals/mips/
          time forge test --mc LiveProposalsIntegrationTest --ffi -vvv
        shell: bash
